import type { Config } from "tailwindcss";

// Design tokens ported verbatim from design/home.html (inline tailwind.config, lines 36-124).
// Do not re-derive these values — see specs/001-phase-0-foundation/research.md.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#713700",
        "surface-bright": "#f4faff",
        tertiary: "#3b3b39",
        "on-tertiary-fixed": "#1b1c1a",
        surface: "#f4faff",
        "surface-dim": "#cfdce4",
        secondary: "#944a00",
        "error-container": "#ffdad6",
        outline: "#717a6d",
        "tertiary-container": "#52524f",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-surface-variant": "#41493e",
        "on-secondary-fixed": "#301400",
        "surface-container-highest": "#d7e4ec",
        "tertiary-fixed": "#e4e2de",
        "primary-fixed-dim": "#91d78a",
        "on-secondary": "#ffffff",
        "inverse-primary": "#91d78a",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ddeaf2",
        "on-primary-fixed-variant": "#0c5216",
        "on-primary-container": "#90d689",
        "inverse-surface": "#263238",
        "primary-container": "#1b5e20",
        "secondary-fixed": "#ffdcc5",
        primary: "#00450d",
        "inverse-on-surface": "#e6f3fb",
        "secondary-container": "#fc8f34",
        "secondary-fixed-dim": "#ffb783",
        background: "#f4faff",
        "surface-container": "#e3f0f8",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-tint": "#2a6b2c",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c0c9bb",
        "on-tertiary-container": "#c6c5c2",
        "on-surface": "#111d23",
        "surface-variant": "#d7e4ec",
        "surface-container-low": "#e9f6fd",
        "on-secondary-container": "#663100",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#474744",
        "primary-fixed": "#acf4a4",
        "on-background": "#111d23",
        "on-primary-fixed": "#002203",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        organic: "20px",
      },
      spacing: {
        "stack-sm": "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-lg": ["plusJakartaSans"],
        "body-md": ["plusJakartaSans"],
        "label-sm": ["plusJakartaSans"],
        "headline-md": ["plusJakartaSans"],
        "display-lg-mobile": ["plusJakartaSans"],
        "display-lg": ["plusJakartaSans"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
